version: 2.1
orbs:
  elixir: membraneframework/elixir@dev:4a0b30c1e512bae86a6c4e89280251b4aae919fa

workflows:
  version: 2
  build:
    jobs:
      - elixir/build_test:
          cache-version: 6
          filters: &filters
            tags:
              only: /v.*/
      - elixir/test:
          cache-version: 6
          filters:
            <<: *filters
      - elixir/lint:
          cache-version: 6
          filters:
            <<: *filters
      - elixir/hex_publish:
          cache-version: 6
          requires:
            - elixir/build_test
            - elixir/test
            - elixir/lint
          context:
            - Deployment
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
